### ISSUE TITLE
Feature Request: Allow add icon:

### ISSUE THREAD

**Issue by poudenes** [cyberjunky/home-assistant-p2000#21]
Hi ALl,

would be nice that you can icon to the sensors so you can use different icons for different sensors.

Cheers

**Comment by golles** [comment]
Hi,

You could customize any entity in HA. I do it in yaml, using the [packages](https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder) method, this is my file:

packages/p2000.yaml
```yaml
sensor:
  - platform: p2000
    name: P2000 Ambulance
    regios: 11
    disciplines: 2
    scan_interval: 120
    radius: 5000
    
  - platform: p2000
    name: P2000 Brandweer
    regios: 11
    disciplines: 1
    scan_interval: 120
    radius: 5000

  - platform: p2000
    name: P2000 Dichtbij
    regios: 11
    disciplines: 1,2,3
    scan_interval: 120
    radius: 250

  - platform: p2000
    name: P2000 Politie
    regios: 11
    disciplines: 3
    scan_interval: 120
    radius: 5000

homeassistant:
  customize:
    sensor.p2000_ambulance:
      icon: "mdi:ambulance"
    sensor.p2000_brandweer:
      icon: "mdi:fire-truck"
    sensor.p2000_dichtbij:
      icon: "mdi:alert"
    sensor.p2000_politie:
      icon: "mdi:taxi"

automation:
  id: p20000_notification
  alias: P2000 melding
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.p2000_dichtbij
  action:
    - service: notify.mobile_app_van_golles
      data_template:
        title: P2000 melding
        message: >
          {{ states.sensor.p2000_dichtbij.state + states.sensor.p2000_dichtbij.attributes.capcodes }}
        data:
          url: "https://www.google.com/maps/search/?api=1&query={{ states.sensor.p2000_dichtbij.attributes.latitude }},{{ states.sensor.p2000_dichtbij.attributes.longitude }}"
  

```
