### ISSUE TITLE
newest update not working (1.0.19)

### ISSUE THREAD

**Issue by canedje** [cyberjunky/home-assistant-p2000#40]
I did just add the newest HACS version.
I do not recieve warnings.

My sensor:
```
#----------------------------------------------------------------      
# Sensoren voor p2000
# Regio 10 = Noord Holland Noord
#----------------------------------------------------------------
    
- platform: p2000
  name: P2000
  regios: 10,11,12
  disciplines: 1,2,3,4
  radius: 5000
  scan_interval: 10
#  capcodes: 1403001,1403003
  icon: mdi:alarm-light

```
This worked with the version before.
What am I doing wrong?

**Comment by cyberjunky** [comment]
Try to remove disciplines, did test those yet.


Op zo 13 jun. 2021 19:40 schreef canedje ***@***.***>:

**Comment by canedje** [comment]
I will test
```
#----------------------------------------------------------------      
# Sensoren voor p2000
# Regio 10 = Noord Holland Noord
#----------------------------------------------------------------
    
- platform: p2000
  name: P2000
  regios: 10,11,12
#  disciplines: 1,2,3,4
  radius: 5000
  scan_interval: 10
#  capcodes: 1403001,1403003
  icon: mdi:alarm-light

```
and will come back with the results

**Comment by canedje** [comment]
No, no results unfortunately.
Somebody at Apeldoorn has it working
I only see the latest warning with the old version:
![image](https://user-images.githubusercontent.com/23150947/121818690-f8fed180-cc88-11eb-8ce3-690d1feffc8c.png)

**Comment by cyberjunky** [comment]
@canedje not all messages have lat/lon yet.
So perhaps use nolocation: True for the time being...
And you have 3 regios but only 5km range, seems a bit odd, only if you live on the central location of the 3 of them...

**Comment by canedje** [comment]
Yes I changed allready the regios to one and removed the radius

**Comment by BebeMischa** [comment]
I have this issue also, and strange, the first sensor works, the other three do not...

```
sensor:
  - platform: p2000
    name: AMS
    regios: 13
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: ZAAN
    regios: 11
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: False

  - platform: p2000
    name: GOOI
    regios: 14
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: False

  - platform: p2000
    name: KNMR
    regios: 12
    disciplines: 1,2,3,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: False
```

![image](https://user-images.githubusercontent.com/73079275/121819493-af64b580-cc8d-11eb-8794-bba8ab66675d.png)

As you see, the other three sensors do not refresh, contains data from before the old RSS feed was gone.

I did restart HA...

So, it looks, like nolocation: False is a pain.

I will now try to set them all to true, but i'm afraid, that it reintroduces old problem - all 4 sensors will show the same event, when no location is given. I will report, how it goes...

**Comment by cyberjunky** [comment]
As I wrote above not all messages don't have locations yet in new feed, zo if you have location: false, this means no updates. Also remove disciples for now 1-4 means alle of them anyway, except knot which you never get. This feed is different so the code works different too.

**Comment by BebeMischa** [comment]
Ok, i've looked specially on the description page, if there are changes, but did not notice any. Thanks for the directions ;-)

**Comment by cyberjunky** [comment]
Rtfm doesn't apply here :-)

**Comment by BebeMischa** [comment]
BTW, your coffee is already freezing cold!

**Comment by BebeMischa** [comment]
Looks better now, but please, give me back my timestamps :-P

But, as I said, now some of the events display for two regio's simultanously, my old irritation is back :-)


![image](https://user-images.githubusercontent.com/73079275/121820039-cbb62180-cc90-11eb-8739-c5f97a74b88f.png)


Code used now:

```
sensor:
  - platform: p2000
    name: AMS
    regios: 13
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: ZAAN
    regios: 11
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: GOOI
    regios: 14
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: KNMR
    regios: 12
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True
```

BTW. do capcode filter still works?

**Comment by cyberjunky** [comment]
Could it be that some messages spread over 2 adjacent regio's? This because the feed and code are really different now, in the old version region was part of the url, now all messages are received and field regio is scanned for correct one.
Capcodes are unique now per event, and in separate field, they should word better , could be that you need the 0 in front (check official capcodes list) and it's not tested yet.

**Comment by BebeMischa** [comment]
That is nice to hear, as it could finally make possible, what we started earlier, filtering out the Lifeliners, as that second integration never got to a reliable state ;-)

**Comment by cyberjunky** [comment]
I think I need to make regio's optional for that to function since lifeliners can operate across them. It's possible now since regio's are not part of url any more.

**Comment by BebeMischa** [comment]
I'm just trying with al regio's listed for that sensor :-)

**Comment by BebeMischa** [comment]
```
sensor:
  - platform: p2000
    name: AMS
    regios: 13
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: ZAAN
    regios: 11
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: GOOI
    regios: 14
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: KNMR
    regios: 12
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: LIFE
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 0120901,1420059,0923993
    scan_interval: 20
    icon: mdi:helicopter
    nolocation: True
```

results in 
![image](https://user-images.githubusercontent.com/73079275/121821600-46d00580-cc9a-11eb-9906-603740b1da62.png)

Tomorrow i will test more... Have to go now. ;-) But again, Ron, DANKJEWEL :-)

**Comment by ernieek** [comment]
I'm stil working on it to get all lon lat filled. So be patiant. Still work in progress 😊

**Comment by BebeMischa** [comment]
Never mind the timestamps. I found a way, using Logbook card,

![image](https://user-images.githubusercontent.com/73079275/121849679-ed90c200-cceb-11eb-848b-8e7a33c68111.png)

**Comment by canedje** [comment]
It is working after adding nolocation: true.

**Comment by BebeMischa** [comment]
Now i only still doubt, if this is correct:

```
capcodes: 0120901,1420059,0923993
```

Or do I need a 0 also by the longer capcode in the middle?

**Comment by BebeMischa** [comment]
Ik, with more of the capcodes as a oneliner it doe's not work. Maybe there is some syntax error, I'm not sure.

So This doe's not work for me, it does not update:

```
 - platform: p2000
    name: LIFE
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 0120901,1420059,0923993
    scan_interval: 20
    icon: mdi:helicopter
    nolocation: True
```

But this doe's work fine now, one sensor per capcode:

```
# Sensors
sensor:
  - platform: p2000
    name: AMS
    regios: 13
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: ZAAN
    regios: 11
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: GOOI
    regios: 14
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    name: KNMR
    regios: 12
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

  - platform: p2000
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    name: LIFE1
    capcodes: 0120901
    scan_interval: 20
    icon: mdi:helicopter
    nolocation: True
    
  - platform: p2000
    name: LIFE2
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 1420059
    scan_interval: 20
    icon: mdi:helicopter
    nolocation: True
    
  - platform: p2000
    name: LIFE3
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 0923993
    scan_interval: 20
    icon: mdi:helicopter
    nolocation: True
    
  - platform: p2000
    name: KNRM Ijmuiden
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 1735099
    scan_interval: 20
    icon: mdi:boat
    nolocation: True
```

And so I finally have exactly, what I wanted. So, @cyberjunky , the second integration, p2000-Lifeliner has become not needed anymore :-)

Result:

![image](https://user-images.githubusercontent.com/73079275/121869729-a19d4780-cd02-11eb-970d-b9fe7a3fd399.png)


Guys, you are hero's! 🥇

**Comment by mobiledude2** [comment]
It’s great to have data inflow again! Much appreciated. Looking forward to map locations and return of radius! Keep up the great work 👍🏻

**Comment by cyberjunky** [comment]
@BebeMischa I think capcodes are 7 chars long, so no leading zero if they are already that length, what do you mean with timestamp missing? There is a time attribute still, but you need something else?
Will test multiple capcodes, maybe even add  support for a capcode file with code and description field?

**Comment by canedje** [comment]
Yes I forgot to mention.
Mobildude2 did already.
I'm also very happy that p2000 app is running again. Thanks for the work your doing for this!!

**Comment by cyberjunky** [comment]
I just found out I use the same event name for all event triggers on the bus, so no wonder the events overwrote each other.

**Comment by canedje** [comment]
just for info.
Your right there are no location values as you metioned:
![image](https://user-images.githubusercontent.com/23150947/121914915-fe185b00-cd32-11eb-91b3-7937a28c01d1.png)

**Comment by cyberjunky** [comment]
There are but not always... being worked on

**Comment by canedje** [comment]
> There are but not always... being worked on

Not pushing here, just for info

**Comment by ernieek** [comment]
as i said :)

I'm stil working on it to get all lon lat filled. So be patiant. Still work in progress

**Comment by BebeMischa** [comment]
> 
> 
> @BebeMischa I think capcodes are 7 chars long, so no leading zero if they are already that length, what do you mean with timestamp missing? There is a time attribute still, but you need something else?
> Will test multiple capcodes, maybe even add support for a capcode file with code and description field?

capcodes, if used solo, only one code per sensor, are working fine. And yes, no extra 0 needed for 7chars codes. I've sorted that out already. They just don't work, if used multiple in one line.

So this works:

```
capcodes: 1735099
```

And this does not:

```
capcodes: 0120901,1420059,0923993
```

With time stamps I mean this.
If I use entities in a lovelace card, they do not display timestamps.  In following pic the first row is a newly refreshed sensor after the update, it does not display time.
The other three are old data before the update. They al have a timestamp.

![afbeelding](https://user-images.githubusercontent.com/73079275/121926928-c7484200-cd3e-11eb-98cc-8e3d1cfc488b.png)

As I do need to see the time of event, I don't use no entities card, but a Logbook card. The time then is displayed:

![afbeelding](https://user-images.githubusercontent.com/73079275/121927094-f3fc5980-cd3e-11eb-836a-6a5ee92020b5.png)

Actualy I still will like to see the entities card display timestamp, as that card uses lot less space ;-)

A capcode selector somehow would be nice too, yes ;-)

**Comment by cyberjunky** [comment]
In 1.0.20 multiple capcodes work it seems

**Comment by mobiledude2** [comment]
How do I use "default" ? in disciplines (Optional): Disciplines to display, separate them by commas. (default = all of them)

is it text in the yaml file? ("disciplines: default" or remove it out of the config?

**Comment by BebeMischa** [comment]
configuration.yaml

if you wan't to select disciplines:

```
sensor:
  - platform: p2000
    name: AMS
    regios: 13
    disciplines: 1,4
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True
```

If you don't, all disciplines will be collected:

``` 
sensor:
  - platform: p2000
    name: AMS
    regios: 13
    scan_interval: 20
    icon: mdi:fire-truck
    nolocation: True

```
