### ISSUE TITLE
Regio 5 doesn't work

### ISSUE THREAD

**Issue by BlackLion87** [cyberjunky/home-assistant-p2000#41]
I am using de p2000 for a while now. Since the new source is implemented, regio 5 doesn't seem to work. While testing, I tried regio 6, that one does work but that isnt my regio.
Thanks for all the work.

**Comment by aavosnl** [comment]
AT here region 6 is not working... every other region works but not region 6. 

This is getting al the regions excluding region 6 

  - platform: p2000
    name: P2000 test brandweer
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    disciplines: Brandweerdiensten
    scan_interval: 10
    nolocation: true

a seperate one for region 6 

  - platform: p2000
    name: VNOG
    regios: 6
    scan_interval: 10
    capcodes: 0806240
    nolocation: true

also not working.

**Comment by golles** [comment]
For this is also no longer working since the source change.
Ambulance and Brandweer haven't updated since 14th of June and Buurt not since 10th of May (Polite doesn't work in my region)

```yaml
sensor:
  - platform: p2000
    name: P2000 Ambulance
    regios: 11
    disciplines: 2
    scan_interval: 120
    radius: 5000
    
  - platform: p2000
    name: P2000 Brandweer
    regios: 11
    disciplines: 1
    scan_interval: 120
    radius: 5000

  - platform: p2000
    name: P2000 Dichtbij
    regios: 11
    disciplines: 1,2,3
    scan_interval: 120
    radius: 250

  - platform: p2000
    name: P2000 Politie
    regios: 11
    disciplines: 3
    scan_interval: 120
    radius: 5000
```
<img width="1149" alt="Schermafbeelding 2021-06-27 om 21 41 27" src="https://user-images.githubusercontent.com/2211503/123557307-83b6f480-d790-11eb-8dd1-e7951f2060a4.png">
