### ISSUE TITLE
Configured icon is being overwritten

### ISSUE THREAD

**Issue by golles** [cyberjunky/home-assistant-p2000#42]
Hi, I migrated my config to support the new version and I'm now using icons in the yaml (before I did by customizing).

I copied Lifeliner config from an other issue (it flies over my house quite often) and just noticed that the helicopter icon changed into an ambulance.

config:
```yaml
  - platform: p2000
    name: P2000 Lifeliner 1
    icon: mdi:helicopter
    regios: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
    capcodes: 0120901
    scan_interval: 60
    nolocation: True
```

State:
```
state: A1 (MKA 12 NH) 13991 Bosboom Toussaintlaan Heemstede Rit 60041
longitude: 4.62169
latitude: 52.34256
distance: 26998
capcode: '0120901'
regio: '13'
regio name: Amsterdam Amstelland
discipline: Ambulancediensten
time: '2021-06-29T14:00:58'
attribution: P2000 Livemonitor 2021 HomeAssistant
friendly_name: P2000 Lifeliner 1
icon: mdi:ambulance
```

I personally find if an icon is defined, it should not get overwritten. Hence this bug report
