### ISSUE TITLE
(variable) Sensor state in message

### ISSUE THREAD

**Issue by jjwerkman** [cyberjunky/home-assistant-p2000#65]
Hi, I'm using the p2000 for notifying me.
I have three triggers (bases on capcodes) in one automation. I know I can sent the sensor state with {{ states('sensor.**sens-name**') }}
But I have three triggers, is there a way to make the value in the message variable so it reflects the state of the sensor for which the automation is triggered?
I've searched the web but didn't find what I was looking for. Hope you can point me in the right direction.

alias: p2000
description: ''
trigger:
  - platform: state
    entity_id: sensor.sens1
    attribute: capcode
  - platform: state
    entity_id: sensor.sens2
    attribute: capcode
  - platform: state
    entity_id: sensor.sens3
condition: []
action:
  - device_id: 5d3b39999999999bc694f55555fc168
    domain: mobile_app
    type: notify
    message: '{{ states('sensor.sens1') }}'
    title: p2000
mode: single

**Comment by jgverweij** [comment]
You can use "{{ trigger.to_state.state }}" for the message.

**Comment by jjwerkman** [comment]
Sorry to say this suggestion doesn’t work. No error in the log. Only when I test the notification, then I receive an error. But found somewhere that that is a normal behavior. Do you have another suggestion to try? Thanks.

**Comment by jgverweij** [comment]
Did you enclose the curly braces between single or double quotes? This does work:

```yaml
alias: 'P2000 multiple triggers'
trigger:
  - platform: state
    entity_id: sensor.<your_sensor_1_here>
  - platform: state
    entity_id: sensor.<your_sensor_2_here>
condition: []
action:
  - service: notify.mobile_app_<your_device_id_here>
    data:
      title: '{{ trigger.to_state.entity_id }}'
      message: '{{ trigger.to_state.state }}'
mode: queued
max: 10
```
